---
- name: Install NGINX
  hosts: servers
  become: true
  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes

    - name: Install required packages
      become: true
      apt:
        name:
          - nginx
        state: present

    - name: Enable nginx service
      become: yes
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Checking Nginx Started and Enabled
      service:
        name: nginx
        state: started
        enabled: yes
